[package]
name = "fast_clipboard_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
fast_clipboard = { path = "../fast_clipboard" }
wl-clipboard-rs = "0.7.0"
env_logger = "0.10.0"
log = "0.4.17"

[[bin]]
name = "daemon"
path = "src/main.rs"
